language: ruby
sudo: false
rvm:
  - 2.2.3
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
before_install:
  - gem --version
webhooks:
  urls:
    - https://webhooks.gitter.im/e/c1b921a7220a9e2edab2
  # options: [always|never|change] default: always
  on_success: change
  on_failure: always
  on_start: never
