default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: citizens_development
  host: localhost
  username: citizens
  password: citizens

test:
  <<: *default
  database: travis_ci_test
  host: localhost
  username: travis
  password: ""

production:
  <<: *default
  database: <%= ENV["CITIZENS_DATABASE_NAME"] %>
  username: <%= ENV["CITIZENS_DATABASE_USERNAME"] %>
  password: <%= ENV["CITIZENS_DATABASE_PASSWORD"] %>
