default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: citizens_development
  username: citizens
  password: citizens

test:
  <<: *default
  database: citizens_test
  username: citizens
  password: citizens

production:
  <<: *default
  database: <%= ENV["CITIZENS_DATABASE_NAME"] %>
  username: <%= ENV["CITIZENS_DATABASE_USERNAME"] %>
  password: <%= ENV["CITIZENS_DATABASE_PASSWORD"] %>
